; -------------------------------------
; interrupt_alignment_check.asm - Version 1.0
; Copyright (c) red031000 2024-11-22
; -------------------------------------

; Alignment check interrupt handler

%include "panic.inc"

bits 64

section .rodata

alignment_check_text:
    db "Interrupt: Alignment Check", 0x0

section .text

global interrupt_alignment_check_handler
interrupt_alignment_check_handler:
    ; Alignment check exceptions are only generated by usermode and they have to be enabled, so nothing can be done
    ; at the moment. it should never occur but if it does panic.

    push rbx
    lea rbx, [rsp + 0x10]
    mov qword[rip_replacement], rbx
    pop rbx

    ; we need to restore the flags
    push qword[rsp + 0x18]
    popfq

    push alignment_check_text

    call panic

    ; panic never returns but iretq is good practice anyway
    iretq
